### ISSUE TITLE
可以播放网络的么

### ISSUE THREAD

**Issue by Alexxiaopang** [ykbjson/simpledlna#1]
如题，能否播放网络地址？

**Comment by ykbjson** [comment]
这个项目本身不涉及到播放视频功能，本地图片视频投屏本身也是转换成网络地址投屏的，理论上是支持的

**Comment by javaertj** [comment]
可以的
` 

         String sourceUrl = mMaxMediaData.getSourceUrl();
          if (mMaxMediaData.isLocalMediaData()) {
              sourceUrl = mMaxMediaData.getLocalVideoPath();
          }
          final MediaInfo mediaInfo = new MediaInfo();
          if (mMaxMediaData.isLocalMediaData()) {
              mediaInfo.setFilePath(sourceUrl);
          }
          mediaInfo.setMediaId(EncryptUtils.encryptMD5ToString(sourceUrl));
          mediaInfo.setMediaType(MediaInfo.TYPE_VIDEO);
          mediaInfo.setMediaName(mMaxMediaData.getTitle());
          mediaInfo.setUri(sourceUrl);
          mDLNAPlayer.setDataSource(mediaInfo);
          mDLNAPlayer.start(new DLNAControlCallback() {
              @Override
              public void onSuccess(@Nullable ActionInvocation invocation) {
                  ToastUtils.showShort("投屏成功！");
                  getContentView().post(new Runnable() {
                      @Override
                      public void run() {
                          dismiss();
                      }
                  });
              }
  
              @Override
              public void onReceived(@Nullable ActionInvocation invocation, @Nullable Object... extra) {
  
              }
  
              @Override
              public void onFailure(@Nullable ActionInvocation invocation, int errorCode, @Nullable String errorMsg) {
                  ToastUtils.showShort("投屏失败！");
              }
          });


`
